# Logging Configuration
level: INFO
format: structured  # json, structured, simple

console:
  enabled: true
  level: INFO
  format: rich
  show_time: true
  show_path: false

file:
  enabled: true
  level: DEBUG
  path: logs/nemesis.log
  encoding: utf-8
  rotation:
    enabled: true
    max_size: 10MB
    backup_count: 5

retention:
  enabled: true
  max_files: 5
  retention_days: 30

sensitive_data:
  enabled: true
  patterns:
    - password
    - passwd
    - token
    - api_key
    - secret